function state = spEmptyState(~, capacity)
%SPEMPTYSTATE Initialise the mutable packing state before any insertion.
%The next progress threshold is advanced only after a successful placement.
validateattributes(capacity, {'numeric'}, {'scalar','integer','nonnegative'});
state=struct('centres',zeros(capacity,3),'radii',zeros(capacity,1), ...
    'cellIndices',zeros(capacity,3),'count',0,...
    'sphereCells',containers.Map('KeyType','char','ValueType','any'),...
    'nextProgressPercent',25);
end
